app = "mathematical-app-4653"
github = "https://github.com/rahul-nife/react-app/archive/refs/heads/main.zip"
id = "dfd2b769ebbf703f5ee17dc6d18594025d0f936b37962a7fbea8a013be350508455a1f77fe7d2702665d25bea8773d89"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "Github"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"
    

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
