name: Deploy to Nife

on:
  push:

jobs:
 scan:
   name: Scan GitHub Secrets
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Scan GitHub Secrets
       uses: kams-mash/gh-secrets-scanner-action@master
       continue-on-error: true  # This ensures the job continues even if this step fails
